
CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASES; --> OPCIONAL

DROP TABLE CLIENTE;/* EXCLUIR TABELA */

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, /* NAO PODE SE REPETIR*/
	NOME VARCHAR(30) NOT NULL, /* NAO PODE SER NULA */
	SEXO ENUM('M', 'F') NOT NULL,/* ENUM SO EXISTE EM SQL */
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,

	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)/* QUER DIZER QUE SO TEM UM CLIENTE PARA UM ENDEREÇO RELAÇÃO 1*1 */
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT, /* NAO TEM UNIQUE PQ É UMA RELAÇÃO DE 1 X N */

	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

INSERT INTO CLIENTE VALUES('DAVI','M','D@GMAIL.COM',034587757,'SHIN BSB');
INSERT INTO CLIENTE VALUES('ANA','F','A@GMAIL.COM',03488887,'SOBREL BSB');
INSERT INTO CLIENTE VALUES('REGI','F','R@GMAIL.COM','0888887','ASA BSB');
INSERT INTO CLIENTE VALUES('MILE','F','M@GMAIL.COM','03477757','NORTE BSB');
INSERT INTO CLIENTE VALUES('NATH','F','N@GMAIL.COM','03555757','SUDOK BSB');
INSERT INTO CLIENTE VALUES('YAN','M','Y@GMAIL.COM','0310101057','SOBRAL BSB');
