
CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASES; --> OPCIONAL

DROP TABLE CLIENTE;/* EXCLUIR TABELA */

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, /* NAO PODE SE REPETIR*/
	NOME VARCHAR(30) NOT NULL, /* NAO PODE SER NULA */
	SEXO ENUM('M', 'F') NOT NULL,/* ENUM SO EXISTE EM SQL */
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,

	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)/* QUER DIZER QUE SO TEM UM CLIENTE PARA UM ENDEREÇO RELAÇÃO 1*1 */
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT, /* NAO TEM UNIQUE PQ É UMA RELAÇÃO DE 1 X N */

	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/* TABELA DE CLIENTE */
INSERT INTO CLIENTE VALUES(NULL,'DAVI','M','D@GMAIL.COM','034587757');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','A@GMAIL.COM','03488887');
INSERT INTO CLIENTE VALUES(NULL,'REGI','F','R@GMAIL.COM','0888887');
INSERT INTO CLIENTE VALUES(NULL,'MILE','F','M@GMAIL.COM','03477757');
INSERT INTO CLIENTE VALUES(NULL,'NATH','F','N@GMAIL.COM','03555757');
INSERT INTO CLIENTE VALUES(NULL,'YAN','M','Y@GMAIL.COM','031010105');

/* TABELA DE ENDERECO */
INSERT INTO ENDERECO VALUES(NULL,'RUA1','BAIRRO1','CIDADE1','E1',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA2','BAIRRO2','CIDADE2','E2',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA3','BAIRRO3','CIDADE3','E3',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA4','BAIRRO4','CIDADE4','E4',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA5','BAIRRO5','CIDADE5','E5',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA6','BAIRRO6','CIDADE6','E6',6);

/* TABELA DE TELEFONE */
INSERT INTO TELEFONE VALUES(NULL,'CEL','9787878781',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','9787878721',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','9787878782',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','9787878783',3);